user:
  name_max_lenght: 50
  email_max_lenght: 255
  password_min_lenght: 6
sessions:
  check_session: "1"
users_page: 
  per_page: 10
users:
  gravatar_size: 50
helper:
  gravatar_size: 80
user_gravatar: 50
maximum_content: 140
hours_expire: 2
img_size: 5
